services:
  fastapi:
    container_name: fastapi
    build:
      context: ../
      dockerfile: Dockerfile
    env_file:
      - ../.env
    tty: true
    ports:
      - "8000:8000"
    networks:
      - dev-net
    volumes:
      - ../src:/app/src


networks:
  dev-net:
    name: dev-net
    driver: bridge